export const GLOBAL_AXIOS_ERROR = 'GLOBAL_AXIOS_ERROR'
export const GLOBAL_AXIOS_INIT = 'GLOBAL_AXIOS_INIT'
export const GLOBAL_AXIOS_SUCCESS = 'GLOBAL_AXIOS_SUCCESS'

export const LOGIN_WITH_FACEBOOK_INIT = 'LOGIN_WITH_FACEBOOK_INIT'
export const LOGIN_WITH_FACEBOOK_ERROR = 'LOGIN_WITH_FACEBOOK_ERROR'
export const LOGIN_WITH_FACEBOOK_SUCCESS = 'LOGIN_WITH_FACEBOOK_SUCCESS'

export const FACEBOOK_GRAPH_REQ_INIT = 'FACEBOOK_GRAPH_REQ_INIT'
export const FACEBOOK_GRAPH_REQ_ERROR = 'FACEBOOK_GRAPH_REQ_ERROR'
export const FACEBOOK_GRAPH_REQ_SUCCESS = 'FACEBOOK_GRAPH_REQ_SUCCESS'

export const GET_USER_TOKEN_INIT = 'GET_USER_TOKEN_INIT'
export const GET_USER_TOKEN_ERROR = 'GET_USER_TOKEN_ERROR'
export const GET_USER_TOKEN_SUCCESS = 'GET_USER_TOKEN_SUCCESS'

export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'

export const GEOLOCATION_REQ_INIT = 'GEOLOCATION_REQ_INIT'
export const GEOLOCATION_REQ_GRANTED = 'GEOLOCATION_REQ_GRANTED'
export const GEOLOCATION_REQ_DENIED = 'GEOLOCATION_REQ_DENIED'

export const GEOLOCATION_GET_LOCATION_INIT = 'GEOLOCATION_GET_LOCATION_INIT'
export const GEOLOCATION_GET_LOCATION_SUCCESS = 'GEOLOCATION_GET_LOCATION_SUCCESS'
export const GEOLOCATION_SERVICE_NOT_ACTIVE = 'GEOLOCATION_SERVICE_NOT_ACTIVE'

export const GET_POSTCARD_BY_LOCATION_INIT = 'GET_POSTCARD_BY_LOCATION_INIT'
export const GET_POSTCARD_BY_LOCATION_SUCCESS = 'GET_POSTCARD_BY_LOCATION_SUCCESS'
export const GET_POSTCARD_BY_LOCATION_NOT_FOUND = 'GET_POSTCARD_BY_LOCATION_NOT_FOUND'
export const GET_POSTCARD_BY_LOCATION_ERROR = 'GET_POSTCARD_BY_LOCATION_ERROR'

export const USER_REGISTRATION_INIT = 'USER_REGISTRATION_INIT'
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS'
export const USER_REGISTRATION_ERROR = 'USER_REGISTRATION_ERROR'
export const REMOVE_REGISTRATION_ERROR = 'REMOVE_REGISTRATION_ERROR'

export const USER_LOGIN_INIT = 'USER_LOGIN_INIT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const REMOVE_LOGIN_ERROR = 'REMOVE_LOGIN_ERROR'

export const REQ_USER_PASS_INIT = 'REQ_USER_PASS_INIT'
export const REQ_USER_PASS_SUCCESS = 'REQ_USER_PASS_SUCCESS'
export const REQ_USER_PASS_ERROR = 'REQ_USER_PASS_ERROR'
export const REMOVE_REQ_USER_PASS_ERROR = 'REMOVE_REQ_USER_PASS_ERROR'

export const CHANGE_USER_PASS_INIT = 'CHANGE_USER_PASS_INIT'
export const CHANGE_USER_PASS_SUCCESS = 'CHANGE_USER_PASS_SUCCESS'
export const CHANGE_USER_PASS_ERROR = 'CHANGE_USER_PASS_ERROR'
export const REMOVE_CHANGE_USER_PASS_ERROR = 'REMOVE_CHANGE_USER_PASS_ERROR'

export const CHANGE_HOME_UPPER_TAB = 'CHANGE_HOME_UPPER_TAB'

export const GET_ALLCATEGORIES_INIT = 'GET_ALLCATEGORIES_INIT'
export const GET_ALLCATEGORIES_SUCCESS = 'GET_ALLCATEGORIES_SUCCESS'
export const GET_ALLCATEGORIES_NOT_FOUND = 'GET_ALLCATEGORIES_NOT_FOUND'
export const GET_ALLCATEGORIES_ERROR = 'GET_ALLCATEGORIES_ERROR'

export const CHANGE_CATEGORY_SEARCH_STRING = 'CHANGE_CATEGORY_SEARCH_STRING'

export const GET_POSTCARD_BY_CATEGORY_INIT = 'GET_POSTCARD_BY_CATEGORY_INIT'
export const GET_POSTCARD_BY_CATEGORY_SUCCESS = 'GET_POSTCARD_BY_CATEGORY_SUCCESS'
export const GET_POSTCARD_BY_CATEGORY_NOT_FOUND = 'GET_POSTCARD_BY_CATEGORY_NOT_FOUND'
export const GET_POSTCARD_BY_CATEGORY_ERROR = 'GET_POSTCARD_BY_CATEGORY_ERROR'

export const CHANGE_GEEPES_INFO = 'CHANGE_GEEPES_INFO'
export const CHANGE_GEEPES_MESSAGE = 'CHANGE_GEEPES_MESSAGE'
export const CHANGE_GEEPES_FONTFAMILY = 'CHANGE_GEEPES_FONTFAMILY'
export const CHANGE_GEEPES_FONTCOLOR = 'CHANGE_GEEPES_FONTCOLOR'
export const CHANGE_GEEPES_MESSAGE_COUNTINFO = 'CHANGE_GEEPES_MESSAGE_COUNTINFO'

export const SEND_CARD_INIT = 'SEND_CARD_INIT'
export const SEND_CARD_SUCCESS = 'SEND_CARD_SUCCESS'
export const SEND_CARD_ERROR = 'SEND_CARD_ERROR'

export const GET_NEW_MSG_INFO = 'GET_NEW_MSG_INFO'
