export const GLOBAL_AXIOS_ERROR = 'GLOBAL_AXIOS_ERROR'
export const GLOBAL_AXIOS_INIT = 'GLOBAL_AXIOS_INIT'
export const GLOBAL_AXIOS_SUCCESS = 'GLOBAL_AXIOS_SUCCESS'

export const LOGIN_WITH_FACEBOOK_INIT = 'LOGIN_WITH_FACEBOOK_INIT'
export const LOGIN_WITH_FACEBOOK_ERROR = 'LOGIN_WITH_FACEBOOK_ERROR'
export const LOGIN_WITH_FACEBOOK_SUCCESS = 'LOGIN_WITH_FACEBOOK_SUCCESS'

export const FACEBOOK_GRAPH_REQ_INIT = 'FACEBOOK_GRAPH_REQ_INIT'
export const FACEBOOK_GRAPH_REQ_ERROR = 'FACEBOOK_GRAPH_REQ_ERROR'
export const FACEBOOK_GRAPH_REQ_SUCCESS = 'FACEBOOK_GRAPH_REQ_SUCCESS'

export const GET_USER_TOKEN_INIT = 'GET_USER_TOKEN_INIT'
export const GET_USER_TOKEN_ERROR = 'GET_USER_TOKEN_ERROR'
export const GET_USER_TOKEN_SUCCESS = 'GET_USER_TOKEN_SUCCESS'

export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'

export const GEOLOCATION_REQ_INIT = 'GEOLOCATION_REQ_INIT'
export const GEOLOCATION_REQ_GRANTED = 'GEOLOCATION_REQ_GRANTED'
export const GEOLOCATION_REQ_DENIED = 'GEOLOCATION_REQ_DENIED'

export const GEOLOCATION_GET_LOCATION_INIT = 'GEOLOCATION_GET_LOCATION_INIT'
export const GEOLOCATION_GET_LOCATION_SUCCESS = 'GEOLOCATION_GET_LOCATION_SUCCESS'
export const GEOLOCATION_SERVICE_NOT_ACTIVE = 'GEOLOCATION_SERVICE_NOT_ACTIVE'

export const GET_POSTCARD_BY_LOCATION_INIT = 'GET_POSTCARD_BY_LOCATION_INIT'
export const GET_POSTCARD_BY_LOCATION_SUCCESS = 'GET_POSTCARD_BY_LOCATION_SUCCESS'
export const GET_POSTCARD_BY_LOCATION_NOT_FOUND = 'GET_POSTCARD_BY_LOCATION_NOT_FOUND'
export const GET_POSTCARD_BY_LOCATION_ERROR = 'GET_POSTCARD_BY_LOCATION_ERROR'